### ISSUE TITLE
Not parsing .osu files, pretty much unusable

### ISSUE THREAD

**Issue by maxerium** [CookieHoodie/OsuBot#2]
Bot launches up all good, I can set the settings without an issue.
But when I try to play a map, it won't grab the .osu file and nothing happens.
No errors pop up either.

**Comment by deezimusnutsimus** [comment]
![kermit](https://user-images.githubusercontent.com/37638505/40582917-d152570c-6150-11e8-969d-a6a64d248b40.png)
heres a fix for you

**Comment by CookieHoodie** [comment]
@meowxi It's weird to have no error but with such behaviour. 

The bot only parses .osu file after you've chosen the bot and the mod (i.e Auto -> Nomod) and see the screen "waiting for beatmap...". So maybe you're not on that screen when you played maps? **You need to get back from the settings screen as well after you've configured the settings to continue the bot.**

Another possibility will be the language problem I've mentioned in the README. If the path to your osu!.exe contains non-English characters or your system language is not in English, such behaviour might happen (?) Idk I haven't tried that.

Anyone else with this problem without meeting the conditions above? If so I'll try to fix that ASAP.

**Comment by maxerium** [comment]
I solved the issues by myself, I just had to go onto **Stable** instead of **Cutting-Edge** and the problem was solved.
