### ISSUE TITLE
Cursor not sinced

### ISSUE THREAD

**Issue by IAmShoxz** [CookieHoodie/OsuBot#3]
I have the problem that my cursor isnt synced with the game at all it only moves in my left top section of my screen (1/4th of the screen i hope u understand what i mean) i tried restarting my game and the bot but all that didnt helped (pc restart didnt helped eather). i play on the Standart osu version and have everything normal relax is the only thing that works for me atm

**Comment by CookieHoodie** [comment]
Make sure you're playing with stable release and have disabled raw input. Try to use different resolution (remember to restart the bot every time you change the resolution and don't move the osu window after the bot is started). The bot just doesn't work for some users for some reason, and I've stopped developing this program so I can't do much about it. So if it still doesn't work for you, perhaps you should try out other bots out there. Thanks for support though.

**Comment by IAmShoxz** [comment]
ok putting it out of fullscreen mode and putting it on 1920x1080 helped ty tho c:
